name: pettrack
description: Lost & Found App for Pets

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  
  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  intl: ^0.20.2
  
  # Image and Location
  image_picker: ^1.1.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  uuid: ^4.5.1
  # State management
  provider: ^6.0.5
  url_launcher: ^6.1.11
  http: ^1.1.0
  cloudinary_public: ^0.23.1
  # flutter_map: ^8.1.1
  # latlong2: ^0.9.1
  # tflite_flutter: ^0.11.0
  # image: ^4.0.17
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  # tflite_flutter: ^0.11.0
  # google_ml_kit: ^0.16.0
  image: ^4.1.3
  # image_picker: ^1.0.7
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0
  share_plus: ^7.1.0
  firebase_messaging: ^15.2.10
  # flutter_local_notifications: ^16.3.2 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon2.png"
